spring.application.name=ledger-api

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com

spring.datasource.url=jdbc:postgresql://localhost:5432/entity_ledger
spring.datasource.username=postgres
spring.datasource.password=Monkeys13!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=TRACE
