spring.application.name=ledger-api

# Frontend URL (Change this in production environments)
frontend.url=http://localhost:5173

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
# Sets the session timeout to 14 days (or you can use hours like 24h)
# server.servlet.session.timeout=14d

spring.datasource.url=jdbc:postgresql://localhost:5432/entity_ledger
spring.datasource.username=postgres
spring.datasource.password=Monkeys13!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=TRACE
